services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    restart: unless-stopped

  test:
    build: .
    command: pytest
    depends_on:
      - redis
    env_file:
      - .env
    restart: "no"  # Only runs when invoked manually

  redis:
    image: redis:7
    restart: unless-stopped
