name: Lint, Format, and Auto-Fix

on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install format/lint tools
        run: |
          pip install black isort flake8

      - name: Auto format with Black
        run: black .

      - name: Auto sort imports with isort
        run: isort .

      - name: Lint with flake8 (won’t fix, only fail if issues remain)
        run: flake8 . || echo "::warning::flake8 found issues"

      - name: Commit & Push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "style: auto-format via GitHub Actions"
          git push
